name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: download
        run: |
          ./pkg/yt-dlp/yt-dlp --config-location config.txt

      - name: upload
        run: |
          ./pkg/transfer/transfer gof ./downloads/